import { ArrowRight, BookOpen, Braces, Database, FileCheck2, GitBranch, ShieldCheck } from "lucide-react";
import { Link } from "wouter";

const steps = [["01", "Capture", "Scan the working tree or paste a focused source/config snippet into the detector."], ["02", "Classify", "Regex patterns identify known formats while Shannon entropy flags high-randomness assignments."], ["03", "Mask", "The value is masked before it becomes a finding payload, log line, or dashboard record."], ["04", "Decide", "High-confidence signals block the merge path. Medium-confidence findings stay visible for review."]];

export default function Docs() {
  return <div className="container py-16 sm:py-24"><div className="max-w-3xl"><p className="eyebrow">Documentation / method</p><h1 className="display-font mt-4 text-5xl font-bold leading-[.98] sm:text-7xl">A small detector with a clear point of view.</h1><p className="mt-7 max-w-2xl text-lg leading-8 text-muted-foreground">Secret Leak Detector is intentionally inspectable. The supplied backend is synchronous where it matters, conservative about what it reads, and designed to make the blocking decision understandable.</p></div><div className="mt-16 grid gap-5 md:grid-cols-2">{steps.map(([number, title, text]) => <article key={number} className="surface border hairline p-7 sm:p-9"><span className="mono-font text-sm text-primary">{number}</span><h2 className="display-font mt-10 text-3xl font-semibold">{title}</h2><p className="mt-4 max-w-md leading-7 text-muted-foreground">{text}</p></article>)}</div><section className="mt-16 grid gap-12 border-t hairline pt-16 lg:grid-cols-[.8fr_1.2fr]"><div><p className="eyebrow">Engine notes</p><h2 className="display-font mt-4 text-4xl font-bold">Evidence over black boxes.</h2></div><div className="grid gap-4 sm:grid-cols-2"><Note icon={<Braces />} title="Supported formats" text="Python, JavaScript, TypeScript, Java, env, YAML, JSON, XML, and common config files." /><Note icon={<GitBranch />} title="Skip paths" text="Dependency directories, build outputs, virtual environments, and binary files are skipped." /><Note icon={<Database />} title="Safe persistence" text="The backend stores masked findings and scan metadata. Raw secret values are never stored." /><Note icon={<FileCheck2 />} title="API shape" text="The original FastAPI backend exposes health, findings, resolve, and stats endpoints for extension." /></div></section><div className="mt-16 flex flex-col items-start justify-between gap-5 border-t hairline pt-8 sm:flex-row sm:items-center"><p className="flex items-center gap-2 text-sm text-muted-foreground"><ShieldCheck size={17} className="text-primary" /> Built to be reviewed by the person who owns the merge.</p><Link href="/scan" className="button-primary">Test the engine <ArrowRight size={16} /></Link></div></div>;
}

function Note({ icon, title, text }: { icon: React.ReactNode; title: string; text: string }) { return <article className="rounded-[2px] border hairline p-5"><span className="flex h-9 w-9 items-center justify-center rounded-full bg-secondary text-primary">{icon}</span><h3 className="mt-5 font-semibold">{title}</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">{text}</p></article>; }
