import { useState } from "react";
import { AlertTriangle, CheckCircle2, FileCode2, LoaderCircle, LockKeyhole, Play, RotateCcw, ShieldAlert } from "lucide-react";
import { trpc } from "../lib/trpc";

const starter = `# paste a source or config snippet here\nAPI_KEY = "replace-with-a-real-secret"\nregion = "us-east-1"\n`;

type ScanResult = Awaited<ReturnType<typeof useScanResult>>;
function useScanResult() { return trpc.scanner.scan.useMutation(); }

export default function Scan() {
  const [source, setSource] = useState(starter);
  const [filename, setFilename] = useState("config.py");
  const scan = useScanResult();
  const result = scan.data;
  const findings = result?.findings ?? [];

  const runScan = () => scan.mutate({ source, filename, repoName: "local-workspace" });

  return <div className="container py-14 sm:py-20"><div className="max-w-3xl"><p className="eyebrow">Live scanner / local workspace</p><h1 className="display-font mt-4 text-5xl font-bold leading-[.98] sm:text-7xl">Put a snippet under the microscope.</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-muted-foreground">This page calls the detector engine from the supplied backend. Your text is sent to the local server process, scanned with regex and Shannon entropy, and returned with masked values.</p></div>
    <div className="mt-12 grid gap-7 lg:grid-cols-[1.15fr_.85fr] lg:items-start"><section className="surface overflow-hidden rounded-[2px] border hairline"><div className="flex flex-wrap items-center justify-between gap-3 border-b hairline px-5 py-4"><div className="flex items-center gap-2"><FileCode2 size={16} className="text-primary" /><span className="mono-font text-xs">source buffer</span></div><div className="flex items-center gap-2"><label htmlFor="filename" className="eyebrow">file</label><input id="filename" value={filename} onChange={event => setFilename(event.target.value)} className="mono-font w-32 border-b border-input bg-transparent px-1 py-1 text-xs outline-none focus:border-primary" /></div></div><textarea value={source} onChange={event => setSource(event.target.value)} spellCheck={false} className="mono-font min-h-[360px] w-full resize-y bg-transparent p-5 text-sm leading-7 outline-none placeholder:text-muted-foreground" aria-label="Source code to scan" /><div className="flex flex-col gap-3 border-t hairline bg-secondary/35 px-5 py-4 sm:flex-row sm:items-center sm:justify-between"><span className="mono-font text-[11px] text-muted-foreground">max 250kb / no raw values persisted</span><button onClick={runScan} disabled={scan.isPending || !source.trim()} className="button-primary disabled:cursor-not-allowed disabled:opacity-60">{scan.isPending ? <><LoaderCircle size={16} className="animate-spin" /> scanning engine</> : <><Play size={15} /> run scan</>}</button></div></section>
      <aside className="space-y-5"><div className="surface rounded-[2px] border hairline p-6"><div className="flex items-center justify-between"><p className="eyebrow">Scan result</p><span className={`flex items-center gap-1.5 text-xs font-semibold ${result?.summary.blocked ? "text-destructive" : result ? "text-primary" : "text-muted-foreground"}`}>{result?.summary.blocked ? <ShieldAlert size={14} /> : result ? <CheckCircle2 size={14} /> : <LockKeyhole size={14} />}{result?.summary.blocked ? "merge blocked" : result ? "clean to merge" : "awaiting input"}</span></div><div className="mt-7 grid grid-cols-3 gap-3"><Metric label="findings" value={result ? String(result.summary.findings).padStart(2, "0") : "—"} /><Metric label="high" value={result ? String(result.summary.high).padStart(2, "0") : "—"} danger /><Metric label="medium" value={result ? String(result.summary.medium).padStart(2, "0") : "—"} /></div>{result && <div className="mt-6 border-t hairline pt-5 text-sm text-muted-foreground">The Python detector scanned <span className="font-semibold text-foreground">{result.files_scanned} file</span> and returned <span className="font-semibold text-foreground">{result.summary.findings} signal{result.summary.findings === 1 ? "" : "s"}</span>. Values shown below are masked by the engine.</div>}</div><div className="surface rounded-[2px] border hairline p-6"><div className="flex items-center gap-2"><AlertTriangle size={16} className="text-primary" /><p className="font-semibold">What counts as a finding?</p></div><ul className="mt-5 space-y-3 text-sm leading-6 text-muted-foreground"><li className="flex gap-3"><span className="mono-font text-primary">01</span><span>Known credential formats: AWS, GitHub, Slack, private keys, and common assignments.</span></li><li className="flex gap-3"><span className="mono-font text-primary">02</span><span>High-entropy assignment values that look random even when they have no known prefix.</span></li><li className="flex gap-3"><span className="mono-font text-primary">03</span><span>High confidence means two independent signals agree.</span></li></ul></div></aside></div>
    {findings.length > 0 && <section className="mt-7 surface overflow-hidden rounded-[2px] border hairline"><div className="flex items-center justify-between border-b hairline px-5 py-4"><p className="eyebrow">Findings / {findings.length}</p><button onClick={() => { scan.reset(); setSource(starter); }} className="button-secondary py-2 text-xs"><RotateCcw size={13} /> reset</button></div><div className="divide-y hairline">{findings.map((finding, index) => <div key={`${finding.file_path}-${finding.line_number}-${index}`} className="grid gap-4 px-5 py-5 sm:grid-cols-[1fr_auto] sm:items-center"><div><div className="flex flex-wrap items-center gap-3"><span className="mono-font text-xs text-primary">{finding.file_path}:{finding.line_number}</span><span className="rounded-full bg-destructive/10 px-2 py-1 text-[10px] font-bold uppercase tracking-[.1em] text-destructive">{finding.confidence}</span></div><p className="mt-2 font-semibold">{finding.secret_type}</p><p className="mono-font mt-1 text-xs text-muted-foreground">{finding.masked_value}</p></div><div className="text-left sm:text-right"><p className="eyebrow">entropy</p><p className="mono-font mt-1 text-sm">{finding.entropy_score.toFixed(2)}</p></div></div>)}</div></section>}
  </div>;
}

function Metric({ label, value, danger = false }: { label: string; value: string; danger?: boolean }) { return <div className="rounded-[2px] bg-secondary/60 p-3"><p className="eyebrow">{label}</p><p className={`display-font mt-2 text-3xl font-bold ${danger ? "text-destructive" : ""}`}>{value}</p></div>; }
